### ISSUE TITLE
Lemma has wrong accent for John 1:46, 8th word

### ISSUE THREAD

**Issue by jonathanrobie** [biblicalhumanities/Nestle1904#1]
John 1:46       τι      X-NSN   X-NSN   5100    τὶς     τι

**Comment by emg** [comment]
Jonathan, do you mean to say that the indefinite pronoun should be accented TI/S or simply TIS?

Or do you mean to say that TI should be accented somehow (the last word on this line)?

The last word on this line is not a lemma, but an attempt at displaying the surface form in a context-independent manner.

Please clarify what you meant. Thanks.

Ulrik

**Comment by jonathanrobie** [comment]
My mistake: I hadn't realized you were using τὶς as the lemma for the indefinite and τίς as the lemma for the interrogative.  Your analysis is good.
