### ISSUE TITLE
Extra comma in 1 Peter 1:13

### ISSUE THREAD

**Issue by jonathanrobie** [biblicalhumanities/Nestle1904#10]
Diego has an extra comma after τελείως in 1 Peter 1:13:

> 13 Διὸ ἀναζωσάμενοι τὰς ὀσφύας τῆς διανοίας ὑμῶν, νήφοντες, τελείως, ἐλπίσατε ἐπὶ τὴν φερομένην ὑμῖν χάριν ἐν ἀποκαλύψει Ἰησοῦ Χριστοῦ. 

I am removing it:

> 13 Διὸ ἀναζωσάμενοι τὰς ὀσφύας τῆς διανοίας ὑμῶν, νήφοντες, τελείως ἐλπίσατε ἐπὶ τὴν φερομένην ὑμῖν χάριν ἐν ἀποκαλύψει Ἰησοῦ Χριστοῦ.

**Comment by emg** [comment]
Hi @jonathanrobie, has Diego (upstream) been notified of this error?

Ulrik

**Comment by jonathanrobie** [comment]
I sent him email.
