### ISSUE TITLE
Need paragraphs

### ISSUE THREAD

**Issue by jonathanrobie** [biblicalhumanities/Nestle1904#5]
We need the paragraphs from the original Nestle1904, which are present in the copy from Diego Santos.

**Comment by jtauber** [comment]
The way I did the database behind api.morphgnt.org was every line has not just a verse ref but a sentence ref and a paragraph ref. The sentence ref comes from GBI. I'd love to have stable refs for these things, especially as much of what I want to do is best done at sentence or paragraph level rather than verse level.

**Comment by jonathanrobie** [comment]
I have downloaded Nestle1904 in both .pdf and .odt formats, I can convert it and maintain formatting information and paragraphs by converting to html with this one-liner:

```
 soffice --convert-to html --outdir html odt/*.odt
```

The result preserves what I want to have, and can easily be converted to Docbook or TEI.   Here's an example of the HTML:

```
<body lang="pt-BR" dir="ltr">
<h1 class="western">ΠΡΟΣ ΓΑΛΑΤΑΣ</h1>
<p class="western" style="margin-bottom: 0in"><br/>

</p>
<h2 class="western">1</h2>
<p class="western" style="margin-bottom: 0in"><br/>

</p>
<p class="western" style="margin-bottom: 0in">	<font color="#000080">1</font>
Παῦλος ἀπόστολος, οὐκ ἀπ’ ἀνθρώπων
οὐδὲ δι’ ἀνθρώπου ἀλλὰ διὰ Ἰησοῦ
Χριστοῦ καὶ Θεοῦ Πατρὸς τοῦ ἐγείραντος
αὐτὸν ἐκ νεκρῶν, <font color="#000080">2</font> καὶ
οἱ σὺν ἐμοὶ πάντες ἀδελφοί, ταῖς
ἐκκλησίαις τῆς Γαλατίας· <font color="#000080">3</font>
χάρις ὑμῖν καὶ εἰρήνη ἀπὸ Θεοῦ Πατρὸς
ἡμῶν καὶ Κυρίου Ἰησοῦ Χριστοῦ, <font color="#000080">4</font>
τοῦ δόντος ἑαυτὸν ὑπὲρ τῶν ἁμαρτιῶν
ἡμῶν, ὅπως ἐξέληται ἡμᾶς ἐκ τοῦ
αἰῶνος τοῦ ἐνεστῶτος πονηροῦ κατὰ
τὸ θέλημα τοῦ Θεοῦ καὶ Πατρὸς ἡμῶν,
<font color="#000080">5</font> ᾧ ἡ δόξα εἰς τοὺς
αἰῶνας τῶν αἰώνων· ἀμήν.</p>
```

It's brain-dead simple to identify book, chapter, and verse.  The formatting also seems to indicate things like quotations.  Although poetry is identifiable, probably not automatically.

I also have a script to automagically download the .odts now.

**Comment by jonathanrobie** [comment]
I checked in an xhtml directory with files automatically converted using wget, soffice, and tidy.  The class names are squirrely, but it's well-formed as XML and also displays properly in the browser, and it's a good format to convert to OSIS - which is my next step.

**Comment by jonathanrobie** [comment]
I have now added paragraphs throughout in the ./xml directory.
